In [693]:
import pandas as pd 
df=pd.read_csv("CNNBSWhileeee.csv");
import numpy as np

In [694]:
df.head(5)
tc=100;
tc=tc+1

print(df.head())

                                                code  tag
0  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...    0
1  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...    0
2  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...    0
3  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...    0
4  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...    0


In [695]:
trainX,train_Y=df['code'],df['tag']

In [696]:
tmp=[]
for i in trainX:
    k=i.split()
    if(len(k)==100):
        k.append(0)
    
        
    a=np.array(k)
    a=a.astype('float32')
    
    
    a=a.reshape(tc,1)
    tmp.append(a)
train_X=np.array(tmp)
train_X.shape
type(train_X[1][1][0])



numpy.float32

In [697]:


train_X.shape

(260, 101, 1)

In [698]:
train_X=train_X/155 
train_X

array([[[0.        ],
        [0.        ],
        [0.        ],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.        ],
        [0.        ],
        [0.        ],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.        ],
        [0.        ],
        [0.        ],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]],

       ...,

       [[0.7677419 ],
        [0.67096776],
        [0.67741936],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.7677419 ],
        [0.67096776],
        [0.67741936],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.7677419 ],
        [0.67096776],
        [0.67741936],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]]], dtype=float32)

In [699]:
train_X = train_X.reshape(-1, tc,1, 1)
train_X.shape

(260, 101, 1, 1)

In [700]:
from keras.utils import to_categorical

In [701]:
train_Y_one_hot = to_categorical(train_Y)
#test_Y_one_hot = to_categorical(test_Y)

# Display the change for category label using one-hot encoding
print('Original label:', train_Y[2])
print('After conversion to one-hot:', train_Y_one_hot[2])


Original label: 0
After conversion to one-hot: [1. 0.]


In [702]:
from sklearn.model_selection import train_test_split
train_X,valid_X,train_label,valid_label = train_test_split(train_X, train_Y_one_hot, test_size=0.15, random_state=13)

In [703]:
train_X.shape,valid_X.shape,train_label.shape,valid_label.shape


((221, 101, 1, 1), (39, 101, 1, 1), (221, 2), (39, 2))

In [704]:
import keras
from keras.models import Sequential,Input,Model
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.layers.normalization import BatchNormalization
from keras.layers.advanced_activations import LeakyReLU

In [705]:
batch_size = 64
epochs = 25
num_classes = 2

In [706]:
binary_model = Sequential()
binary_model.add(Conv2D(16, kernel_size=(4, 1),activation='linear',input_shape=(tc,1,1),padding='same'))
binary_model.add(LeakyReLU(alpha=0.1))
binary_model.add(MaxPooling2D((2, 1),padding='same'))
binary_model.add(Dropout(0.2))
binary_model.add(Conv2D(32, (2, 1), activation='linear',padding='same'))
binary_model.add(LeakyReLU(alpha=0.1))
binary_model.add(MaxPooling2D(pool_size=(2, 1),padding='same'))
binary_model.add(Dropout(0.2))
binary_model.add(Flatten())
binary_model.add(Dense(128, activation='linear'))
binary_model.add(LeakyReLU(alpha=0.1))                  
binary_model.add(Dense(num_classes, activation='softmax'))

In [707]:
binary_model.compile(loss=keras.losses.categorical_crossentropy, optimizer=keras.optimizers.Adam(),metrics=['accuracy'])

In [708]:
binary_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_31 (Conv2D)           (None, 101, 1, 16)        80        
_________________________________________________________________
leaky_re_lu_46 (LeakyReLU)   (None, 101, 1, 16)        0         
_________________________________________________________________
max_pooling2d_31 (MaxPooling (None, 51, 1, 16)         0         
_________________________________________________________________
dropout_31 (Dropout)         (None, 51, 1, 16)         0         
_________________________________________________________________
conv2d_32 (Conv2D)           (None, 51, 1, 32)         1056      
_________________________________________________________________
leaky_re_lu_47 (LeakyReLU)   (None, 51, 1, 32)         0         
_________________________________________________________________
max_pooling2d_32 (MaxPooling (None, 26, 1, 32)         0         
__________

In [709]:
binary_train = binary_model.fit(train_X, train_label, batch_size=batch_size,epochs=epochs,verbose=1,validation_data=(valid_X, valid_label))

Train on 221 samples, validate on 39 samples
Epoch 1/25
221/221 [==============================] - 2s 8ms/step - loss: 0.6869 - acc: 0.6290 - val_loss: 0.6566 - val_acc: 0.7179
Epoch 2/25
221/221 [==============================] - 0s 326us/step - loss: 0.6562 - acc: 0.7195 - val_loss: 0.6283 - val_acc: 0.7179
Epoch 3/25
221/221 [==============================] - 0s 326us/step - loss: 0.6273 - acc: 0.7195 - val_loss: 0.5999 - val_acc: 0.7179
Epoch 4/25
221/221 [==============================] - 0s 308us/step - loss: 0.5981 - acc: 0.7285 - val_loss: 0.5839 - val_acc: 0.8462
Epoch 5/25
221/221 [==============================] - 0s 317us/step - loss: 0.5932 - acc: 0.6923 - val_loss: 0.5549 - val_acc: 0.7949
Epoch 6/25
221/221 [==============================] - 0s 321us/step - loss: 0.5566 - acc: 0.7602 - val_loss: 0.5418 - val_acc: 0.7949
Epoch 7/25
221/221 [==============================] - 0s 326us/step - loss: 0.5249 - acc: 0.7557 - val_loss: 0.5414 - val_acc: 0.7949
Epoch 8/25
221/221 

In [710]:
test_eval =binary_model.evaluate(train_X, train_label, verbose=0)

In [711]:
print('Test loss:', test_eval[0])
print('Test accuracy:', test_eval[1])

Test loss: 0.30450342238219075
Test accuracy: 0.8959275999220249


In [712]:
from sklearn.metrics import classification_report
predicted_classes=binary_model.predict(valid_X)
#print(predicted_classes)

In [713]:
predicted_classes = np.argmax(np.round(predicted_classes),axis=1)


In [714]:
predicted_classes


array([0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0], dtype=int64)

In [715]:
actual= np.argmax(np.round(valid_label),axis=1)

In [716]:
actual

array([1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0], dtype=int64)

In [717]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(predicted_classes,actual))

             precision    recall  f1-score   support

          0       0.74      0.85      0.79        20
          1       0.81      0.68      0.74        19

avg / total       0.77      0.77      0.77        39



In [718]:

def cleanData(c):
    code=c
    df1 = pd.DataFrame({'A':[code]})
            
    df1 = df1.replace('\n',' ', regex=True)
    df1 = df1.replace('\t',' ', regex=True)
    df1 = df1.replace('\r',' ', regex=True)
    df1 = df1.replace(',',' ', regex=True)
    c=0
    tmp=""
    for i in df1['A']:
                c=0
                aa=i.split()
                ff=0
                #print(aa)
                for it in aa:
                    if "while" in it:
                        ff=1
                        #print("While found at",it)
                    if ff==1:
                        for xx in it:
                            
                            if c<=100:
                                tmp=tmp+str(ord(xx))+' '
                                #print(ord(xx),end=' ')
                                c=c+1
                    if "lower_bound" in it :
                        for xx in it:
                            
                            if c<=100:
                                tmp=tmp+str(ord(xx))+' '
                                #print(ord(xx),end=' ')
                                c=c+1
                    if "upper_bound" in it :
                        for xx in it:
                            
                            if c<=100:
                                tmp=tmp+str(ord(xx))+' '
                                #print(ord(xx),end=' ')
                                c=c+1
                while(c<=100):
                    tmp=tmp+"0 "
                    #print(0,end=' ')
                    c=c+1
                        
               
            
    #print(ff)          
    return tmp
            
    
    

In [719]:
def makeCNNReady(c):
    tmp=[]
    tmp=c.split()
    aa=np.array(tmp)
    aa=aa.astype('float32')
    
    aa=aa.reshape(tc,1)
    aa=aa.reshape(-1,tc,1,1)
    aa=aa/155
    return aa

In [720]:
def getPrediction(c):
    pred=binary_model.predict(makeCNNReady(cleanData(c)))
    print(pred)
    #cc=np.argmax(np.round(pred),axis=1)
    if pred[0][1]>=pred[0][0]:
        return "yes"
    else:
        return "no"

In [721]:
code="""
#include<bits/stdc++.h>
using namespace std;
int main()
{

while(l<=r)
{
int mid=(l+r)/2;
if(a[mid]==k)
else if(a[mid]<k)
r=mid-1;
else if(a[mid]>k)
l=mid+1;
}
}

}


"""

In [722]:
#cleanData(code)
getPrediction(code)


[[0.06224575 0.9377542 ]]


'yes'

In [723]:
code="""

#include <iostream>
#include <cstdio>
#include <algorithm>
#include <cstring>
using namespace std;
const int maxn = 2e5+8;
int n,a[maxn],dp1[maxn],len1[maxn],dp2[maxn],h1[maxn],h2[maxn],len2[maxn];
int main(){
    scanf("%d",&n);
    for(int i = 1;i <= n;++i)
        scanf("%d",&a[i]),a[i] -= i;
    int mx = 1;
    memset(dp1,0x3f,sizeof(dp1));
    for(int i = 1;i <= n;++i){
        int idx = upper_bound(dp1+1,dp1+1+n,a[i]) - dp1;
        dp1[idx] = a[i];
        mx = max(mx,idx);
        len1[i] = mx;
        h1[i] = dp1[mx];
    }
    memset(dp2,0x3f,sizeof(dp2));
    mx = 1;
    for(int i = n;i >= 1;--i){
        int idx = upper_bound(dp2+1,dp2+1+n,-a[i]-1) - dp2;
        dp2[idx] = -a[i]-1;
        mx = max(mx,idx);
        len2[i] = mx;
        h2[i] = dp2[mx];
    }
    dp1[0] = 0;dp2[0] = -2;
    int ans = max(len1[n],len2[1]);
    for(int i = 1;i <= n;++i){
        //printf("i:%d len1:%d len2:%d dp1:%d dp2:%d\n",i,len1[i-1],len2[i+1],h1[i-1],h2[i+1]);
        if(h1[i-1] <= -h2[i+1]){
            ans = max(ans,len1[i-1]+len2[i+1]);
        }
    }
    cout<<max(0,n-1-ans)<<endl;
    return 0;
}








"""

In [724]:
getPrediction(code)

[[0.16536406 0.834636  ]]


'yes'

In [725]:
code="""
#include<bits/stdc++.h>
using namespace std;
int main()
{

while(t--)
{
cin>>n;
if(n%2==0)
cout<<"Even"<<endl;
else
cout<<"Odd"<<endl;

}
}

"""



In [726]:
getPrediction(code)

[[0.7468583  0.25314164]]


'no'

In [727]:
code="""

#include<bits/stdc++.h>
using namespace std;
int main()
{
int t,n,k,i,x;
cin>>t;
while(t--)
{
cin>>n>>k;
x=0;
for(i=0;i<n;i++)
{
cin>>a[i];
if(a[i]%2==0)
x=1;
}



}

}




"""

In [728]:
#print(cleanData(code))
print(getPrediction(code))


[[0.82901704 0.170983  ]]
no


In [729]:
tt=makeCNNReady(cleanData(code))


In [730]:
tt.shape

(1, 101, 1, 1)

In [731]:
tt=tt/155

In [732]:
getPrediction(code)

[[0.82901704 0.170983  ]]


'no'

In [733]:
print(code)



#include<bits/stdc++.h>
using namespace std;
int main()
{
int t,n,k,i,x;
cin>>t;
while(t--)
{
cin>>n>>k;
x=0;
for(i=0;i<n;i++)
{
cin>>a[i];
if(a[i]%2==0)
x=1;
}



}

}







In [734]:
#x=makeCNNReady(cleanData(code))
#print(x)
getPrediction(code)

[[0.82901704 0.170983  ]]


'no'

In [735]:
code="""

#include<bits/stdc++.h>
using namespace std;
int main()
{
        ios_base::sync_with_stdio(0);
        cin.tie(0);
        cout.tie(0);
        cin>>n>>k;
        for(i=0;i<n;i++)
        cin>>a[i];
        while(i<n)
        {
            if(a[i]==k)
            {
                cout<<i<<endl;
                break;
            }
            i++;
        }
        
        
}






"""


In [736]:
cleanData(code)

'119 104 105 108 101 40 105 60 110 41 123 105 102 40 97 91 105 93 61 61 107 41 123 99 111 117 116 60 60 105 60 60 101 110 100 108 59 98 114 101 97 107 59 125 105 43 43 59 125 125 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 '

In [737]:
getPrediction(code)

[[0.7084807  0.29151928]]


'no'